---
# tasks file for install

- fail:
    msg: Unsupported OS
  when: {{ ansible_distribution }} != 'centos' or {{ ansible_distribution }} != 'redhat'

- debug: 
    msg: "{{ ansible_distribution }} detected"

- fail:
    msg: "{{ ansible_distribution }} is not 7"
  when: {{ major_release }} != 7
  

- name: Set selinux permissive
  command: setenforce permissive

- name: Installing epel repo
  yum:
    name: epel-release
    state: latest
  when: {{ ansible_distribution }} != 'centos'

# ToDo if ostype is redhat check for subscription manajor.

- name: Check to see if the .creds file exists, supply default if it does not
  stat:
    path: /custom/conf/hda/.creds
  register: check_creds

- name: take defaults if .creds is not present
  file:
    path: /custom/conf/hda
    state: directory
  when: check_creds.stat.exists == false

- name: Copy the .creds file from config to hda directory
  copy: 
    src: ./config/.creds
    dest: /custom/conf/hda
    mode: 600
  when: check_creds.stat.exists == false

- name: setting up config.sh
  command: awk -f ./util/readproperties.awk < /custom/conf/hda/.creds >> ./config.sh
  when: {{ vm }} == 'single'

- name: source the config.sh
  command: source ./config.sh

